name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest || (
            echo "composer install failed, trying composer update..."
            composer update --prefer-dist --no-progress --no-suggest
          )
      - name: Check phpunit.xml.dist
        run: |
          if [ ! -f phpunit.xml.dist ]; then
            echo "phpunit.xml.dist not found! Please add it to the project root."
            exit 1
          fi
      - name: Run tests
        run: |
          if [ ! -f vendor/bin/phpunit ]; then
            echo "phpunit not installed! Please check composer.json require-dev."
            exit 1
          fi
          ./vendor/bin/phpunit --configuration phpunit.xml.dist